### ISSUE TITLE
Was this broken recently?

### ISSUE THREAD

**Issue by joncalhoun** [foss-haas/vsc-fontsize-shortcuts#2]
This plugin worked for me at one point, but no longer appears to :(

VSCode seems to be trying to override the shortcuts or something for their zoom, even when I disable the default shortcuts for zooming. Any suggestions on how to fix it?

**Comment by joncalhoun** [comment]
Sorry - a full quit and reopening of vscode appears to have fixed the issue. I just wish I knew why it stopped working in the first place.

**Comment by pluma** [comment]
Weird. I have had some conflicts with the shortcuts on occasion because of other extensions before, though. You might want to double-check the shortcut settings.

**Comment by joncalhoun** [comment]
I'm guessing VSCode updated or something in the background and caused an issue b/c the shortcuts were doing the default zooming (even though I removed those shortcuts)

Thanks though! Really appreciate the extension.

**Comment by pluma** [comment]
np, Peter did all the hard work, I'm just picking up the torch for him.
